/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  overview: [{type: 'autogenerated', dirName: 'overview'}],
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],

  // But you can create a sidebar manually


  // overviewsidebar: [
  //   'overview/intro',
  //   {
  //     type: 'category',
  //     label: 'Deployments',
  //     items: ['overview/onpremise', 'overview/hosted', 'overview/fod'],
  //   },
    
  // ],

  // tutorialSidebar: [
  //   'tutorials/intro',
  //   {
  //     type: 'category',
  //     label: 'Tutorials',
  //     items: ['tutorials/tutorial-basics/create-a-document'],
  //   },
  // ],
   
};

module.exports = sidebars;
